# Generated by Django 2.2.4 on 2019-12-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20191213_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=5000)),
                ('owner_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Signal_User_Profile')),
            ],
        ),
    ]
