# Generated by Django 2.2.4 on 2019-12-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191030_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal_user_profile',
            name='channel_link',
            field=models.CharField(default='https://www.youtube.com/channel/UCZ9qFEC82qM6Pk-54Q4TVWA', max_length=1000),
            preserve_default=False,
        ),
    ]
