# Generated by Django 2.2.4 on 2019-12-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_signal_user_profile_channel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal_user_profile',
            name='has_survey_complete',
            field=models.IntegerField(default=False),
        ),
    ]
