# Generated by Django 2.2.4 on 2019-12-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_signal_user_profile_has_survey_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal_user_profile',
            old_name='channel_link',
            new_name='channel_url',
        ),
    ]
