# Generated by Django 2.2.4 on 2019-12-14 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191213_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal_user_profile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 14, 13, 41, 14, 109166)),
        ),
    ]
