# Generated by Django 2.2.4 on 2019-12-14 13:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_signal_user_profile_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal_user_profile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 14, 13, 41, 54, 908277, tzinfo=utc)),
        ),
    ]
