# Generated by Django 2.2.4 on 2019-12-14 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191214_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal_user_profile',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
