# Generated by Django 2.2.4 on 2019-12-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191214_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal_user_profile',
            name='survey_points',
            field=models.IntegerField(default=0),
        ),
    ]
