# Generated by Django 2.2.4 on 2019-12-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('accounts', '0009_signal_user_profile_survey_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal_user_profile',
            name='owned_comments',
            field=models.ManyToManyField(to='dashboard.Comment'),
        ),
    ]
