# Generated by Django 2.2.4 on 2019-12-14 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_signal_user_profile_owned_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal_user_profile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 14, 14, 37, 27, 685075, tzinfo=utc)),
        ),
    ]
