# Generated by Django 2.2.4 on 2019-12-15 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191214_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal_user_profile',
            name='is_on_survey',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='signal_user_profile',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
